server.port=8082
spring.application.name=servicio-pedido

# Configuración H2 en memoria
spring.datasource.url=jdbc:h2:mem:pedidodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true